name: Update WinGet Packages

on: workflow_dispatch

jobs:
  update:
    name: Update Package
    runs-on: ubuntu-latest
    steps:
    - name: Update Packages
      uses: michidk/winget-updater@v1
      with:
        komac-token: ${{ secrets.KOMAC_TOKEN }}
        identifier: "HydrusNetwork.HydrusNetwork"
        repo: "hydrusnetwork/hydrus"
        URL: "https://github.com/hydrusnetwork/hydrus/releases/download/v607a/Hydrus.Network.{VERSION}.-.Windows.-.Installer.exe"
